# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link_with_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('chat_id', models.CharField(max_length=40)),
                ('get_notice', models.BooleanField(default=True)),
            ],
        ),
    ]
